### ISSUE TITLE
Jar包直接使用

### ISSUE THREAD

**Issue by void0720** [0opslab/opslabJutil#11]
可不可以直接导入jar包就可以使用里面的所有API，目前只测试了下面一段代码，就发现类找不到
public static void main(String[] args){
	String string = ChinesUtil.getFullSpell("你好");
	System.out.println(string);
}
异常信息
Exception in thread "main" java.lang.NoClassDefFoundError: net/sourceforge/pinyin4j/format/exception/BadHanyuPinyinOutputFormatCombination

**Comment by 0opslab** [comment]
这个是基于pinyin4j的，你看pom文件里面写清楚了依赖的jar

**Comment by void0720** [comment]
不是，我知道pom文件中有所依赖的jar包，我的意思是把pom文件中所依赖的jar包下载下来，打包到整个工程中生成一个jar包，这样就可以直接一个jar包调用所有的方法了，那样我们在项目中使用的时候只需要将你的jar包导入到工程中就可以了

**Comment by 0opslab** [comment]
@void0720 以前我也这么想过，但是后面发现一个文件,那样如果jar冲突了就不好找，因此才这么做的，并且大家都是这么做的！所以！

**Comment by void0720** [comment]
好的，了解了，支持……
