### ISSUE TITLE
ArrayUtil doueleBitCount

### ISSUE THREAD

**Issue by kimmil** [0opslab/opslabJutil#14]
该方法没有考虑科学计数法的问题

 public static int doueleBitCount(double dd)
    {
        String temp = String.valueOf(dd);
        int i = temp.indexOf(".");
        if (i > -1)
        {
            return temp.length() - i - 1;
        }
        return 0;
        
    }
    
    public static void main(String[] args)
    {
        Double a = 3.4E10;
        System.out.println(a);
        System.out.println(doueleBitCount(a));
    }

**Comment by kimmil** [comment]
这样就可以了
public static int doueleBitCount(double dd)
    {
        String temp = String.valueOf(dd);
        BigDecimal bd = new BigDecimal(temp);
        String str = bd.toPlainString();
        System.out.println(str);
        int i = str.indexOf(".");
        if (i > -1)
        {
            return str.length() - i - 1;
        }
        return 0;
        
    }
    
    public static void main(String[] args)
    {
        Double a = 3.0123456789E9;
        System.out.println(a);
        System.out.println(doueleBitCount(a));
    }

**Comment by 0opslab** [comment]
ok,下次更新下！非常感谢
