### ISSUE TITLE
建议：使用POM结构管理吧

### ISSUE THREAD

**Issue by zhxxcq** [0opslab/opslabJutil#2]

**Comment by 0opslab** [comment]
这个可以的,我之所以选在现在的结构不适用maven是因为这样更让结构更加清晰些！
我也在纠结这个问题 有时候github下载很慢，是不是考虑使用maven不将jar更新到github上！
看下次不行我就改成maven组织的方式

**Comment by zhxxcq** [comment]
直接改吧，这个项目还是不错的。支持。

**Comment by 0opslab** [comment]
决定，五一前全都改好！

**Comment by mushroomgithub** [comment]
好东西，把项目使用pom打成jar以后，可以考虑上传maven仓库，以后可以直接通过maven仓库下载

**Comment by 0opslab** [comment]
@mushroomgithub 
这个可以考虑，五一的时候尽量搞定

**Comment by 0opslab** [comment]
@zhxxcq 话说cpdetector这个包貌似很多仓库都没有！这是一个很老的包了,不知道是否有好的替代品

**Comment by zhxxcq** [comment]
@0opslab cpdetector目前用到哪些功能了。还有要考虑支持JDK1.8了。

**Comment by 0opslab** [comment]
@zhxxcq cpdetector主要用来做了些编码探测的功能!

**Comment by 0opslab** [comment]
@zhxxcq  maven 慢的跟鬼一样...

**Comment by zhxxcq** [comment]
@0opslab 不错，把idea的相关文件也去掉。没必要上传这些文件

**Comment by 0opslab** [comment]
@zhxxcq 恩！等maven那边审核通过了，我统一修改！倒是可以直接通过maven来使用
